### ISSUE TITLE
Unable to install flash

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/Flash#1]
**Expected behavior**
Should be able to install flash

**Actual behavior**
Getting 
```
Failed to install plugin 'flash'.
Reason: Invalid plugin. Could not download flash-install.json file.
```

**Steps to replicate**
* gauge install flash

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
screenshot (0.0.1)
```

**Comment by sriv** [comment]
I am able to install it using `gauge install flash` on Windows 10.

**Comment by sswaroopgupta** [comment]
This issue was because Flash is not available on the nightly channel.

Alternative -
Using flash file install
