### ISSUE TITLE
Run fails when flash port is used

### ISSUE THREAD

**Issue by marius-uncrop** [getgauge/Flash#8]
### $ gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
flash (0.0.2)
html-report (4.0.9)
python (0.3.7)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

FLASH_SERVER_PORT = 5678

### Steps to reproduce:
1. Start running some tests
2. While the first run is in progress, run another tests

### Expected results:
Flash should silently fail that the port is used and the execution should continue

## Actual results:
Run execution fails when flash tries to access port
`gauge run specs/sanity/login/login.spec --log-level debug --machine-readable --fail-safe 
{"type":"out","message":"gauge run specs/sanity/login/login.spec"}
{"type":"out","message":"fail-safe : [true]"}
{"type":"out","message":"log-level : [debug]"}
{"type":"out","message":"machine-readable : [true]"}
{"type":"out","message":"'gauge_environment' set to 'default'"}
{"type":"out","message":"Created gauge_screenshots_dir at /home/marius/workspace/auto/figtesting/website_sanity_tests/.gauge/screenshots"}
{"type":"out","message":"Plugin flash is already installed."}
{"type":"out","message":"Plugin xml-report is already installed."}
{"type":"out","message":"Plugin python is already installed."}
{"type":"out","message":"Plugin html-report is already installed."}
{"type":"out","message":"Plugin spectacle is already installed."}
{"type":"out","message":"Parsing started."}
{"type":"out","message":"Started concepts parsing."}
{"type":"out","message":"102 concepts parsing completed."}
{"type":"out","message":"Started specifications parsing."}
{"type":"out","message":"1 specifications parsing completed."}
{"type":"out","message":"Parsing completed."}
{"type":"out","message":"Staring python runner"}
{"type":"out","message":"Checking updates..."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/flash?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Python: 3.5.3"}
{"type":"out","message":"Loading step implemetations from /home/marius/workspace/auto/figtesting/website_sanity_tests/step_impl dirs."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/html-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/python?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/screenshot?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/spectacle?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/xml-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Starting TCP server.."}
{"type":"out","message":"Connecting to port 40515"}
{"type":"out","message":"Established connection to runner."}
{"type":"out","message":"Validation started."}
{"type":"out","message":"Validation completed."}
{"type":"out","message":"Run started"}
{"type":"suiteStart"}
{"type":"out","message":"Starting Html Report plugin"}
{"type":"out","message":"Attempting to connect to grpc server at port: 41105"}
{"type":"out","message":"Successfully made the connection with plugin with port: 41105"}
{"type":"out","message":"Starting Flash plugin"}
{"type":"out","message":"[Flash] Starting progress reporting at http://127.0.0.1:5678"}
{"type":"out","message":"2020/02/24 09:13:22 listen tcp 127.0.0.1:5678: bind: address already in use"}
{"type":"out","message":"Error occurred while waiting for plugin process to finish."}
{"type":"out","message":"Error : exit status 1"}`

### Notes:
Execution continues successfully when using flash version 0.0.1
See output:
`$ gauge run specs/sanity/login/login.spec --log-level debug --machine-readable --fail-safe 
{"type":"out","message":"gauge run specs/sanity/login/login.spec"}
{"type":"out","message":"fail-safe : [true]"}
{"type":"out","message":"log-level : [debug]"}
{"type":"out","message":"machine-readable : [true]"}
{"type":"out","message":"'gauge_environment' set to 'default'"}
{"type":"out","message":"Created gauge_screenshots_dir at /home/marius/workspace/auto/figtesting/website_sanity_tests/.gauge/screenshots"}
{"type":"out","message":"Plugin flash is already installed."}
{"type":"out","message":"Plugin xml-report is already installed."}
{"type":"out","message":"Plugin python is already installed."}
{"type":"out","message":"Plugin html-report is already installed."}
{"type":"out","message":"Plugin spectacle is already installed."}
{"type":"out","message":"Parsing started."}
{"type":"out","message":"Started concepts parsing."}
{"type":"out","message":"102 concepts parsing completed."}
{"type":"out","message":"Started specifications parsing."}
{"type":"out","message":"1 specifications parsing completed."}
{"type":"out","message":"Parsing completed."}
{"type":"out","message":"Staring python runner"}
{"type":"out","message":"Checking updates..."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/flash?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Python: 3.5.3"}
{"type":"out","message":"Loading step implemetations from /home/marius/workspace/auto/figtesting/website_sanity_tests/step_impl dirs."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/html-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/python?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
marius@debian:~/workspace/auto/figtesting/website_sanity_tests$ gauge run specs/sanity/login/login.spec --log-level debug --machine-readable --fail-safe 
{"type":"out","message":"gauge run specs/sanity/login/login.spec"}
{"type":"out","message":"fail-safe : [true]"}
{"type":"out","message":"log-level : [debug]"}
{"type":"out","message":"machine-readable : [true]"}
{"type":"out","message":"'gauge_environment' set to 'default'"}
{"type":"out","message":"Created gauge_screenshots_dir at /home/marius/workspace/auto/figtesting/website_sanity_tests/.gauge/screenshots"}
{"type":"out","message":"Plugin spectacle is already installed."}
{"type":"out","message":"Plugin flash is already installed."}
{"type":"out","message":"Plugin xml-report is already installed."}
{"type":"out","message":"Plugin python is already installed."}
{"type":"out","message":"Plugin html-report is already installed."}
{"type":"out","message":"Parsing started."}
{"type":"out","message":"Started concepts parsing."}
{"type":"out","message":"102 concepts parsing completed."}
{"type":"out","message":"Started specifications parsing."}
{"type":"out","message":"1 specifications parsing completed."}
{"type":"out","message":"Parsing completed."}
{"type":"out","message":"Staring python runner"}
{"type":"out","message":"Checking updates..."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/flash?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Python: 3.5.3"}
{"type":"out","message":"Loading step implemetations from /home/marius/workspace/auto/figtesting/website_sanity_tests/step_impl dirs."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/html-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/python?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/screenshot?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/spectacle?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/xml-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Starting TCP server.."}
{"type":"out","message":"Connecting to port 36927"}
{"type":"out","message":"Established connection to runner."}
{"type":"out","message":"Validation started."}
{"type":"out","message":"Validation completed."}
{"type":"out","message":"Run started"}
{"type":"suiteStart"}
{"type":"out","message":"Starting Html Report plugin"}
{"type":"out","message":"Attempting to connect to grpc server at port: 44503"}
{"type":"out","message":"Successfully made the connection with plugin with port: 44503"}
{"type":"out","message":"Starting Flash plugin"}
{"type":"out","message":"Established connection to Flash plugin"}
{"type":"out","message":"[Flash] Starting progress reporting at http://127.0.0.1:5678"}
{"type":"out","message":"2020/02/24 09:14:54 listen tcp :5678: bind: address already in use"}
{"type":"out","message":"Starting Xml Report plugin"}
{"type":"out","message":"Attempting to connect to grpc server at port: 45711"}
{"type":"out","message":"Successfully made the connection with plugin with port: 45711"}
{"type":"out","message":"Initialising suite data store."}
{"type":"out","message":"Unable to connect to plugin Flash 0.0.1. [Warning] Failed to send message to plugin: flash  write tcp 127.0.0.1:44723-\u003e127.0.0.1:50318: write: broken pipe"}
{"type":"out","message":""}
{"type":"out","message":"Killing Plugin Flash 0.0.1"}
{"type":"out","message":""}
{"type":"out","message":"Failed to kill plugin Flash 0.0.1. os: process already finished"}
{"type":"out","message":""}
{"type":"specStart"`

**Comment by BugDiver** [comment]
@marius-uncrop I just tested it out. And found out that the execution continues after some time.
It waits for the `flash` plugin to exit and then continues the execution after some time.

**Comment by marius-uncrop** [comment]
@BugDiver , is there a configurable timeout for waiting flush plugin?
Note that I only encounter this with version 0.0.2 of the flash plugin and I didn't change anything in the properties files

**Comment by BugDiver** [comment]
@marius-uncrop I could see the error with flash v0.0.1 as well. And it's a valid error since the port is already being used by another run.

v0.0.2 might be taking a little bit more time since it needs to start gRPC server (which in general takes a lil bit more time that opening TCP sockets).

> is there a configurable timeout for waiting for the flash plugin?

You can change the `plugin_connection_timeout` by running `gauge config plugin_connection_timeout <time in milisecond>`
The default timeout for the plugins is `10000` ms.

**Comment by BugDiver** [comment]
Ideally, if you are executing two suits parallelly ( or same suite parallelly) You should you two different ports for the flash server.
